spring.application.name=logistics-api
spring.h2.console.enabled=true

# Give the database a static, predictable name so we can log into it!
spring.datasource.url=jdbc:h2:mem:nearmadedb
spring.datasource.username=sa
